name: spear-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0=pyhd8ed1ab_0
  - anyio=4.3.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39ha55989b_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - blas=2.121=mkl
  - blas-devel=3.9.0=21_win64_mkl
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py39h99910a6_1
  - bzip2=1.0.8=hcfcfb64_5
  - c-ares=1.27.0=hcfcfb64_0
  - ca-certificates=2024.2.2=h56e8100_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py39ha55989b_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.1=py39h99910a6_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - filelock=3.13.1=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - grpcio=1.62.1=py39hd28a505_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.4=pyhd8ed1ab_0
  - httpx=0.27.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.2=pyha770c72_0
  - importlib_metadata=7.0.2=hd8ed1ab_0
  - importlib_resources=6.3.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyha63f2e9_0
  - ipython=8.18.1=pyh7428d3b_3
  - ipywidgets=8.1.2=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - json5=0.9.22=pyhd8ed1ab_0
  - jsonpointer=2.4=py39hcbf5309_3
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.21.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.4=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hcbf5309_0
  - jupyter_events=0.9.1=pyhd8ed1ab_0
  - jupyter_server=2.13.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.1.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.25.4=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.10=pyhd8ed1ab_0
  - libabseil=20240116.1=cxx17_h63175ca_2
  - libblas=3.9.0=21_win64_mkl
  - libcblas=3.9.0=21_win64_mkl
  - libffi=3.4.2=h8ffe710_5
  - libgrpc=1.62.1=h5273850_0
  - libhwloc=2.9.3=default_haede6df_1009
  - libiconv=1.17=hcfcfb64_2
  - liblapack=3.9.0=21_win64_mkl
  - liblapacke=3.9.0=21_win64_mkl
  - libprotobuf=4.25.3=h503648d_0
  - libre2-11=2023.09.01=hf8d8778_2
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.45.2=hcfcfb64_0
  - libuv=1.48.0=hcfcfb64_0
  - libxml2=2.12.5=hc3477c8_0
  - libzlib=1.2.13=hcfcfb64_5
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py39ha55989b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2024.0.0=h66d3029_49657
  - mkl-devel=2024.0.0=h57928b3_49657
  - mkl-include=2024.0.0=h66d3029_49657
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msys2-conda-epoch=20160418=1
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.2=pyhd8ed1ab_0
  - nbformat=5.10.3=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numpy=1.26.4=py39hddb5d58_0
  - openssl=3.2.1=hcfcfb64_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - protobuf=4.25.3=py39h018ea92_0
  - psutil=5.9.8=py39ha55989b_0
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.9.18=h4de0772_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytorch=2.2.1=py3.9_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=306=py39h99910a6_2
  - pywinpty=2.0.13=py39h99910a6_0
  - pyyaml=6.0.1=py39ha55989b_1
  - pyzmq=25.1.2=py39h7eaf5a6_0
  - re2=2023.09.01=hd3b24a8_2
  - referencing=0.33.0=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.7.1=pyhd8ed1ab_0
  - rpds-py=0.18.0=py39hf21820d_0
  - scipy=1.12.0=py39hddb5d58_2
  - send2trash=1.8.2=pyh08f2357_0
  - setuptools=68.2.2=py39haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=pyh04b8f61_3
  - tbb=2021.11.0=h91493d7_1
  - tensorboard=2.16.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py39hcbf5309_1
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4=py39ha55989b_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240315=pyhd8ed1ab_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - ucrt=10.0.22621.0=h57928b3_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - werkzeug=3.0.1=pyhd8ed1ab_0
  - wheel=0.41.2=py39haa95532_0
  - widgetsnbextension=4.0.10=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - winpty=0.4.3=4
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.5=h63175ca_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - pip:
    - cloudpickle==3.0.0
    - contourpy==1.2.0
    - cycler==0.12.1
    - dm-control==1.0.16
    - dm-env==1.6
    - dm-tree==0.1.8
    - etils==1.5.2
    - farama-notifications==0.0.4
    - fonttools==4.49.0
    - fsspec==2024.2.0
    - glfw==2.7.0
    - gymnasium==0.29.1
    - imageio==2.34.0
    - kiwisolver==1.4.5
    - klampt==0.9.1.post4
    - labmaze==1.0.6
    - lxml==5.1.0
    - matplotlib==3.8.3
    - mjcf2urdf==0.0.1
    - mujoco==3.1.3
    - pandas==2.2.1
    - pillow==10.2.0
    - pybullet==3.2.6
    - pyopengl==3.1.7
    - pyopengl-accelerate==3.1.7
    - pyparsing==3.1.2
    - pyqt5==5.15.10
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.13.0
    - pyqtgraph==0.13.4
    - stable-baselines3==2.2.1
    - tzdata==2024.1
